(tmod TEST-CHECK is
    including TEST .
    including TLTLR-MODEL-CHECKER .

    vars GS GS' : GlobalSystem .

    op state : State -> Prop [ctor] .
    eq GS |= state(GS') = GS == GS' .

    vars QID1 QID2 : Qid .
    op action : Qid -> Action [ctor] .
    eq { CTX:StateContext | QID1 : SUB:StateSubstitution } |= action(QID2) = QID1 == QID2 .

    op phi : -> Formula .
    eq phi = [] [1, 2] (state({a(0)}) \/ state({b(1)}) \/ state({c(1)}) \/ state({d(2)})) .
endtm)
